#Parameters for MTB model
metadata:
 save_every: 50 #Saving every ith step
 filename: mtb_testing_o2 #Base filename for h5 output. Will be appended with B, B_phi, T values.
 o2_init_time: 10 #Time at which oxygen is initialized in the system. Before this time, c is set to c_min everywhere. In timesteps.
grid:
 Lx: 4e3 #Box length in um 
 Ly: 2e3 #Box length in um
 Nx: 100
 Ny: 50 #Nx and Ny such that dx dy is aprox 20 um
 T: 100 #Total runtime
 dt: 5e-2 #Timestep in seconds

diff:
 D_o2: 2120 #Diffusion of oxygen in water in um**2/s
 D_bact: 1000 #Diffusion of self-propelling bacteria (ecoli) in water in um**2/s
 D_r: 100.5 #Rotational diffusion in rad**2/s
 gamma_r: 0.1 #1.2e-3 #Rotational drag for bacteria. Relaxation timescale (1/how long until reorienting from a tumble) in s**-1
 beta_p: 0.3 #Sensitivity to chemotactic reorientation torque. 

o2:
 c0_o2: 216 #Oxygen concentration at the H2O/O2 interface in uM
 ca_o2: 0.75 #Oxygen concentration at which bacteria consumption halves in uM
 copt_o2: 10 #Oxygen concentration optimal for bacteria (will search this) in uM
 cmin_o2: 1e-6 #Oxygen concentration (min) to avoid 1/0 divisions in uM

bact:
 p: 5.2e-5 #Proliferating rate for bacteria in 1/s
 k_cons: 1.66e-12 #Consumption rate in uM per second per cell
 K: 1.0 #Maximum bacterial density in 1 O.D. (Optical Density)
 chi: 280 #Chemotactic sensitivity in um**2/s (Cremer et al.)
 b0: 0.3 #Initial bacteria concentration in the inoculum or homogeneous initial conditions
 mu: 1.2e-3 #Magnetic moment of bacteria, sensitivity to the external magnetic field in microT
 v0: 10 #Self-propelling velocity of bacteria in um/s

magnetism:
 B_phi: 45 #Angle with respect to x axis. In degrees, 0 directed in +x, 180 in -x
 B: 500 #Magnetic field magnitude in microT

